name: release

on:
  push:
    branches:
      - "!*"
    tags:
      - "v*.*.*"

permissions: write-all

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Code
        uses: actions/checkout@v3.5.2

      - name: Set up Golang
        uses: actions/setup-go@v4.0.1
        with: { go-version: "1.20" }

      - name: Release Application
        uses: goreleaser/goreleaser-action@v4.2.0
        with:
          version: latest
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
